---
title: Elevate360 Wellness
timezone: UTC
collections:
  about-us:
    title: About Us
    output: true
  authors:
    title: Authors
    output: true
  home:
    title: Home
    output: true
  posts:
    title: Posts
    output: true
  staff:
    title: Staff
    output: true
    layout: default
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    author:
    post_image:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: authors
  values:
    permalink: "/blog/authors/:title/"
    layout: author
    credentials: Ph.D.
    medium:
description: Elevate360 is a boutique addiction treatment program in Midtown Manhattan.
url: https://elevate360.com/
show_excerpts: false
date_format: "%b %-d, %Y"
permalink: pretty
<<<<<<< HEAD
image: https://elevate360.com/assets/images/seo.png
=======
image: "/assets/images/seo.png"
>>>>>>> a60673c24efbba7ba3130b7c29896a296173bf81
twitter:
  username: elevate360NYC
plugins:
- jekyll-seo-tag
- jekyll-sitemap
