---
title: Elevate360 Wellness
timezone: America/New_York
collections:
  about-us:
    title: About Us
    output: false
  authors:
    title: Authors
    output: true
  home:
    title: Home
    output: false
  how-we-treat:
    title: How We Treat
    output: true
    permalink: "/services/how-we-treat/:name"
  posts:
    title: Posts
    output: true
  resources-media:
    title: Media
    output: false
  resources-publications:
    title: Publications
    output: false
  staff:
    title: Staff
    output: true
    permalink: "/about-us/our-staff/:title/"
  therapies-used:
    title: Therapies Used
    output: true
    permalink: "/services/therapies-used/:name/"
  trainings:
    title: Trainings for Clinicians
    output: true
    permalink: "/services/trainings-for-clinicians/:name/"
  treatment-programs:
    title: Treatment Programs
    output: true
    permalink: "/services/treatment-programs/:name/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title/"
    author: 
    post_image: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: authors
  values:
    permalink: "/blog/authors/:title/"
    layout: author
    credentials: Ph.D.
    medium: 
description: Elevate360 is a boutique addiction treatment program in Midtown Manhattan.
seo_subtitle: Outpatient addiction treatment in Midtown Manhattan
url: https://elevate360.com
show_excerpts: false
date_format: "%b %-d, %Y"
permalink: pretty
twitter:
  username: elevate360NYC
facebook:
  app_id: 560591311065650
  publisher: 1306167409485389
mailchimp_url: https://elevate360.us18.list-manage.com/subscribe/post?u=67197f5bd0a1decb3d98c97cc&id=c67e0a1c54
formcarry_form_id: s1U09JSk80i
formcarry_email_subject: An email from your website!
assets:
  sources:
  - _uploads
plugins:
- jekyll-assets
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- Gemfile.lock
- node_modules
- ".gitignore"
- ".ruby-version"
- README.md
- Rakefile
