---
title: Elevate360 Wellness
timezone: America/New_York
collections:
  about-us:
    title: About Us
    output: true
  authors:
    title: Authors
    output: true
  home:
    title: Home
    output: true
  how-we-treat:
    title: How we Treat
    output: true
    layout: default
  posts:
    title: Posts
    output: true
  staff:
    title: Staff
    output: true
    layout: default
  therapies-used:
    title: Therapies Used
    output: true
    layout: default
  trainings:
    title: Trainings for Clinicians
    output: true
    layout: default
  treatment-programs:
    title: Treatment Programs
    output: true
    layout: default
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    author: 
    post_image: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: authors
  values:
    permalink: "/blog/authors/:title/"
    layout: author
    credentials: Ph.D.
    medium: 
description: Elevate360 is a boutique addiction treatment program in Midtown Manhattan.
seo_subtitle: Outpatient addiction treatment in Midtown Manhattan
url: https://elevate360.com
show_excerpts: false
date_format: "%b %-d, %Y"
permalink: pretty
twitter:
  username: elevate360NYC
facebook:
  app_id: 560591311065650
  publisher: 1306167409485389
assets:
  sources:
  - _uploads
plugins:
- jekyll-assets
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- Gemfile.lock
- node_modules
- ".gitignore"
- ".ruby-version"
- README.md
