---
title: Elevate360 Wellness
description: Elevate360 is a boutique outpatient addiction treatment center located in Midtown Manhattan.
url: elevate360.com
timezone: UTC
collections:
  about-us:
    title: About Us
    output: true
  authors:
    title: Authors
    output: true
  home:
    title: Home
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    author:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: authors
  values:
    permalink: "/blog/authors/:title/"
    layout: author
    credentials: Ph.D.
    medium:
description: Elevation360 Wellness website
show_excerpts: false
minima:
  date_format: "%b %-d, %Y"
theme: minima
permalink: pretty
twitter:
  username: elevate360NYC
  card: summary
plugins:
- jekyll-seo-tag
